export const clientTypes = {
  Clash: "clash",
  Surge: "surge&ver=4",
  Surge3: "surge&ver=3",
  Quantumult: "quan",
  QuantumultX: "quanx",
  Singbox: "singbox",
  Loon: "loon",
  Surfboard: "surfboard",
  "Shadowsocks(SIP002)": "ss",
  "Shadowsocks(SIP008)": "sssub",
  Mellow: "mellow",
  ShadowsocksR: "ssr",
  ShadowsocksD: "ssd",
  Surge2: "surge&ver=2",
  V2Ray: "v2ray",
  Trojan: "trojan",
  "混合订阅(mixed)": "mixed",
  自动判断客户端: "auto",
};
