name: Build
on:
  workflow_dispatch:
  push:
concurrency:
  group: Github CI
  # 自动取消其他运行中的workflow
  # cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get dependencies and build
        run: |
          yarn install
          yarn build
      - name: Upload
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dist
          path: dist/
      - name: Push update to subconverter
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'subconverter',
              workflow_id: 'sub-web.yml',
              ref: 'main',
            });
